name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://Umfragen ihts.supabase.co/rest/v1/doodle_votes" \
          -H "apikey: DEIN_KEY"
